# Generated by Django 4.0.4 on 2022-05-25 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memo',
            },
        ),
        migrations.RenameField(
            model_name='taskrecords',
            old_name='time',
            new_name='time_total_second',
        ),
        migrations.RemoveField(
            model_name='taskrecords',
            name='study_at',
        ),
        migrations.AddField(
            model_name='taskrecords',
            name='study_at_local',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrecords',
            name='study_at_utc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrecords',
            name='time_hour',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrecords',
            name='time_min',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskConductTime',
        ),
    ]
