# Generated by Django 4.0.4 on 2022-05-26 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_memo_rename_time_taskrecords_time_total_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecords',
            name='study_at_utc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
