# Generated by Django 4.0.4 on 2022-05-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0003_alter_taskrecords_study_at_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecords',
            name='study_at_utc',
        ),
    ]
